-- DROP tables
DROP TABLE IF EXISTS interventions CASCADE;
DROP TABLE IF EXISTS factures CASCADE;
DROP TABLE IF EXISTS devis CASCADE;
DROP TABLE IF EXISTS actions CASCADE;
DROP TABLE IF EXISTS actions_contenues CASCADE;
DROP TABLE IF EXISTS actions_survenues CASCADE;
DROP TABLE IF EXISTS types_pieces CASCADE;
DROP TABLE IF EXISTS pieces CASCADE;
DROP TABLE IF EXISTS requetes CASCADE;
DROP TABLE IF EXISTS modeles_voitures CASCADE;
DROP TABLE IF EXISTS compositions CASCADE;
DROP TABLE IF EXISTS voitures CASCADE;
DROP TABLE IF EXISTS adresses CASCADE;
DROP TABLE IF EXISTS personnes CASCADE;
DROP TABLE IF EXISTS garages CASCADE;
DROP TABLE IF EXISTS tarifs CASCADE;